### ISSUE TITLE
Opening PPW-coloured private windows colours non-private windows wrong

### ISSUE THREAD

**Issue by eberhardweber** [WaldiPL/purplePrivateWindows#2]
This is my favourite add-on (I can't make out the new private window indicators in FF57 at all, leading to constant mistakes) with one caveat: 

As soon as I open a PPW-coloured private window, it immediately touches up on the non-private window CSS as well. I have set the "dark" theme option for normal windows in PPW, but it doesn't alleviate the problem.

As soon as PPW activates, all other window colours in the dark theme are kind of inverted, like so: https://i.imgur.com/HgFq5ir.png (above is normal, below after PPW). The top colour is removed and the borders seem to go missing.

I am fairly sure this ultimately has to do with my personal userChrome.css customizations, but it seems strange that PPW would override them in the normal windows. Is there something I can do about this?

**Comment by WaldiPL** [comment]
I know about this problem, it is related to a bug in Firefox. To minimize its effects, I added settings. Currently, you can not add a blue bar. Side border is possible from version 58.

**Comment by WaldiPL** [comment]
The problem no longer exists. Tested on: Firefox 69, Purple Private Windows 1.1

**Comment by Slater91** [comment]
The problem appears to be back with Firefox 91.

**Comment by WaldiPL** [comment]
I cannot reproduce this bug. What theme are you using for normal windows? Are you using any other extensions that change the theme?

**Comment by Slater91** [comment]
I am using system theme and I have no other theme-changing extensions.
I am using Firefox on Linux.

**Comment by yura-pakhuchiy** [comment]
@WaldiPL I confirm the issue is back in Ubuntu 18.04 with Firefox 91. I'm using slightly modified Ambiance theme for GTK and system theme in firefox. Theme changes to Adwaita-dark GTK for main window when I open private windows.

**Comment by yura-pakhuchiy** [comment]
I've checked the extension source code, indeed seems like a Firefox bug :-(

**Comment by yura-pakhuchiy** [comment]
@Slater91 not really a fix, but downgrading the plugin to v1.0 and forcing light theme on non-private windows kinda works for me (still looks not perfect).
